### ISSUE TITLE
Separate Name Tables For Sources

### ISSUE THREAD

**Issue by BrandonKMLee** [meodai/color-names#107]
e.g. assuming I don't want names from user submissions, only colors from standardized sources X11/Microsoft/Crayola/Japanese...

That way it is easier to pick colors without too much worry that the same sounding too over the top.

**Comment by meodai** [comment]
It would be very complex to maintain, because:

Most of those lists have: Overlaps in a) color values b) names and sometimes c) both.
So when merged into a single list you would to have to keep track why you kept one over the other and why.

Also the list is cleaned up to have a standardized grammar and we remove offensive, sexist and other names that don't fit the rules. 

- So If you want "quality" names only use the best-of subset. 
- If you only want a specific name list; use this specific list not this one.

**Comment by meodai** [comment]
@BrandonKMLee If you want to start csv's that map current name > to source. I am happy to accept your pull request.
