### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by mariohmol** [meodai/color-names#118]
First of all, AWESOME module, ty!

I would like know if that is any effort of having all the color name list in a way where we can send translations.

For instance, I need these collors to show in portuguese language.

Any ideas on how to achieve that?

Thanks a lot!

**Comment by meodai** [comment]
Hello @tajmone feel free to share your solution here. I always wanted to add a "Tag" document. Where we could track Language, and the source of the names for example

**Comment by tajmone** [comment]
> Hello @tajmone feel free to share your solution here.

I'm not sure how easy that would be. For one thing, the bigger colors lists source in English are names from colors catalogs of actual paints produced by various manufacturers, and I'm not sure how translating them might play out (e.g. if they have legal claims over some of those colors names, and whether they have already translated them to other languages).

Also, colors are strongly tied to culture rather then physical perception of the eye. I've read about a tribe that doesn't have a word for the orange color, they only have red and yellow, and it turned out that when presented with an orange and red books they would see just two red books (they didn't perceive the difference in color as we usually do in our culture). Also, Eskimos have over 30 names for tints of whites, because it's the predominant color in their environment, and natives from the Sub Sahara region have over 16 names for shades of yellow. 

Colors are strictly tied to language and culture, so translations don't always overlap. A clear example of this is that many colors names are borrowed from our natural surroundings (trees, flowers, fruits), which is why some colors seem foreign to one culture yet familiar to another, even if they speak the same language, due to geographic differences. Color names like "sky blue" could indicate quite different colors, depending on the latitude the speaker lives in (possibly a lighter blue the closer you get to the Equator, and a lighter shade the further you move from it).

Instead of speaking of translations of colors, it would make more sense to focus on creating lists of how colors are called in different languages, and they digital representation (be it in Hex format, or whatever other color format).

Other than that, the best solution would be a database, where people are free to add their translation proposals. As usual, the best sources of color names are paint catalogs (car paints, home paints, or artists pencils and markers, etc.).
