### ISSUE TITLE
Add behr color names

### ISSUE THREAD

**Issue by meodai** [meodai/color-names#86]
Did not find a good way to automate the import, maybe there is a more parsable list somewhere?
https://www.behr.com/consumer/colors/paint/explore/all-colors/orange/3

**Comment by cheesits456** [comment]
After a quick look through the `F12` tools, i found [this file](https://www.behr.com/mainrefreshservice/services/color2019/all.js) - just what we're looking for. I downloaded that file, then added the following code to the bottom of it:
```js
// Function to capitalize first letter of each word in a string
function capitalize(text) {
	let r = text.toLowerCase().replace(/(?<=\s)\w/g, c => c.toUpperCase());
	return r.replace(/^\w/, c => c.toUpperCase());
}

const fs = require("fs");

// First array element isn't color data, remove it
colorData.shift();

// Construct list of colors
let list = {};
for (const color of colorData) {
	list[capitalize(color[19])] = color[2].toLowerCase();
}

// Sort object alphabetically by key name
const sorted = {};
Object.keys(list).sort((a, b) => a.localeCompare(b, "en", { sensitivity: "base" })).forEach(key => {
  sorted[key] = list[key];
});

// Write data to new JSON file
fs.writeFileSync("colors.json", JSON.stringify(sorted, null, "\t"), "utf8");
```
Then I ran the file using `node all.js`. Below is a link to the outputted `colors.json` file (uploaded as `colors.txt` because GitHub doesn't allow `.json` files for some reason...). The file is sorted alphabetically by color name and has the following structure:
```json
{
    "Color Name": "#1a2b3c"
}
```
### [colors.txt](https://github.com/meodai/color-names/files/4956793/colors.txt)

**Comment by meodai** [comment]
So cool! 

To make sure I only add the color names that are not already in, I usually run: https://github.com/meodai/color-names/blob/master/scripts/tools/filterUniques.js do you want to do this and submit a PR with the new names?

In case some of the hex values are already taken, I usually just shift them around a bit.

**Comment by cheesits456** [comment]
should this issue be closed now that it's complete?

**Comment by meodai** [comment]
done in b515716986fcf374de51932f13820ab1d0348270
